/* SPDX-License-Identifier: MIT */
/*
 * Copyright (c) 2025 HiSilicon Technologies Co., Ltd. All rights reserved.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 */

#ifndef __U_UTOOL_ERROR_H__
#define __U_UTOOL_ERROR_H__

#define UTOOL_OK 0
#define UTOOL_ERR 1
#define UTOOL_ERR_MALLOC 2
#define UTOOL_ERR_INVALID_PARAM 3
#define UTOOL_ERR_INVALID_CMD 4
#define UTOOL_ERR_IOCTL 5
#define UTOOL_ERR_PARSE 6
#define UTOOL_ERR_CMD_NOT_FOUND 7
#define UTOOL_ERR_CAL_REG_CNT 8
#define UTOOL_ERR_FUNC_NOT_FOUND 9
#define UTOOL_ERR_OPEN_FILE 10
#define UTOOL_ERR_WRITE_FILE 11
#define UTOOL_ERR_READ_FILE 12
#define UTOOL_ERR_HELP 13

#endif
